[workspace]
members = ["rust/mmx-wallet", "rust/mmxwallet"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.85"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
sha2 = "0.10"
hex = "0.4"
zeroize = { version = "1", features = ["derive"] }
