[Service]
# Restrict CUDA and OpenCL to the RTX 4060 Ti.
Environment=CUDA_VISIBLE_DEVICES=GPU-cfe9318e-bfdd-87d9-2c9d-ee75322e2747
ExecStart=
ExecStart=/home/mad/mmx-node/run_node.sh -c config/server/ --Node.opencl_device_name "NVIDIA GeForce RTX 4060 Ti" --Node.opencl_device 0 --cuda.devices [0] --cuda.enable true
