[package]
name = "mmx-wallet"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
zeroize.workspace = true
hmac = "0.12"
k256 = { version = "0.13", features = ["ecdsa"] }
rand = "0.8"
thiserror = "2"
